import { StyleSheet } from "react-native";
const shadow = {
    shadowColor: "#000",
    shadowOffset:{
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
}
export const styles =  StyleSheet.create({
    Body:{
        flex:1,
        backgroundColor:'#F5EFE7',
        width:390
    },
    input:{
        width:320,
        height:55,
        backgroundColor:'white',
        borderRadius:10,
        marginTop:15,
        paddingLeft:20,
    },
    button:{
        backgroundColor:'#3669C9',
        borderRadius:10,
        width:300,
        height:60,
        alignItems:'center',
        justifyContent:'center',
        marginTop:20,
        marginLeft:10
    },
    buttonText:{
        color:'white',
        fontSize:19
    },
    inputRow:{
        marginTop:80,
        paddingLeft:32
    },
    tabRow:{
        height:48,
        backgroundColor:'#D8C4B6',
        borderRadius:5,
        margin:10,
        width:334,
        padding:10,
        alignSelf:'center',
        flexDirection:'row',
        ...shadow,
    },
    tabButton:{
        width:33,
        height:33,
    },
    image:{
        width:23,
        height:23,
        marginTop:3,
        marginLeft:3
    },
    userButton:{
        flexDirection:'row',
        marginLeft:100,
        width:116,
        height:31,
        backgroundColor:'#F5EFE7',
        ...shadow,
        borderRadius:23,
        alignItems:'center',
        paddingLeft:7
    },
    userNick:{
        color:'black',
        fontSize:12,
        marginRight:5
    },
    categoryButton:{
        backgroundColor:'#3669C9',
        width:120,
        height:40,
        borderRadius:5,
        alignItems:'center',
        justifyContent:'center',
        marginLeft:10
    },
    buttonText:{
        color:'white',
        fontSize:15        
    },

    profilRow:{
        width:46,
        height:46,
        marginLeft:14,
        marginTop:11,
        flexDirection:'row',
        backgroundColor:'#F5EFE7',
        borderRadius:10,
        paddingLeft:3,
        paddingTop:3
    },
    gary:{
        color:'gray'
    },
    elegateRow:{
        width:334,
        height:69,
        justifyContent:'space-between',
        borderRadius:5,
        marginHorizontal:5,
        alignSelf:'center',
        paddingLeft:9,
        backgroundColor:'#D8C4B6'
    },
    elegateTitle:{
        marginLeft:128,
        color:'#3F3F3F',
        fontSize:15,
        fontWeight:'700',
        marginTop:3
    },
    elegateButton:{
        backgroundColor:'#F5EFE7',
        width:156,
        height:35,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:5,
        marginRight:4
    },
    elegaButtonRow:{
        flexDirection:'row',
        paddingBottom:4
    },
    elegateButtonText:{
        color:'#D8C4B6',
        fontSize:16,
        fontWeight:'900'
    }
})